In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import make_regression

In [7]:
x,y = make_regression(n_samples=500, n_features=5, coef=False, bias=12, noise=10, random_state=2529)

In [8]:
x,y,w = make_regression(n_samples=500, n_features=5, coef=True, bias=12, noise=10, random_state=2529)

In [9]:
x.shape, y.shape

((500, 5), (500,))

In [10]:
w

array([29.45661718, 60.14529878, 61.7409438 , 13.32437893, 99.08122896])

In [11]:
x.shape, y.shape

((500, 5), (500,))

In [12]:
x[0:5]

array([[ 0.77913208, -1.09701784, -0.14239962,  1.02427891, -1.0708024 ],
       [-0.6925009 ,  0.45535977,  0.34707569, -0.32456746,  0.21970203],
       [-0.03901601, -0.3265115 ,  0.59793721,  0.61686653, -0.6237489 ],
       [-0.61566117, -0.11782129, -0.98234619, -0.78292727,  0.42713048],
       [ 1.30822207, -0.72541559,  0.60187975,  0.33285998,  1.48506184]])

In [13]:
y[0:5]

array([-136.21858395,   49.83118244,  -29.81097858,  -31.74001475,
        193.0687778 ])

In [14]:
x.shape, y.shape

((500, 5), (500,))

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_test, X_train, y_test, y_train = train_test_split(x,y, test_size=0.3, random_state =2529)

In [18]:
X_test.shape, X_train.shape, y_test.shape, y_train.shape

((350, 5), (150, 5), (350,), (150,))

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
model = LinearRegression()

In [21]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
model.intercept_

11.928897130208709

In [23]:
model.coef_

array([30.2834353 , 61.00332749, 61.17922836, 13.65456369, 98.95152746])

In [24]:
y_pred = model.predict(X_test)

In [25]:
y_pred.shape

(350,)

In [26]:
y_pred

array([ 193.08618243,  -46.11748618,  145.37905131,  250.34675423,
         81.99819642,   -7.42959059,  143.25674473,    9.1380423 ,
       -233.47344257,  -19.85223345,  -52.73042155,  -74.66613375,
       -157.37520999,  135.90599714, -152.12557821,   87.80940636,
        174.66382363,   30.99004312,  -56.35418153, -121.3022102 ,
        -14.62324076,   95.42218518,   49.85242407, -295.15458964,
        121.65497118, -147.64186959,   84.42407079, -199.86012615,
        195.61032458,  -49.78669478,  130.07751278, -166.78099609,
         -3.08277004,   57.27789948,   56.07478746,   48.11880729,
        107.85333017, -107.01226358,  -22.92245057,   -1.29641519,
        160.45304468,  108.08399691,  153.77871411,  307.51947941,
       -250.49944511,  -94.63784575,   -5.93209696,  -80.4220211 ,
        302.95691592,  -15.69941864, -209.07987488,  175.59026879,
        -61.38321715,   40.506081  , -107.72671398, -204.2622268 ,
         26.04091748,  155.17130397,   86.37855138,    6.27551

In [30]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [31]:
mean_squared_error(y_test,y_pred)

102.39133719714687

In [32]:
mean_absolute_error(y_test,y_pred)

8.271610016334655

In [33]:
r2_score(y_test,y_pred)

0.9945268594609746